### PR TITLE
Adding Pose2Point2BearingRange elements to Tutorial 1

### PR DESCRIPTION
**Pull request by GearsAD**
Resolves 
- https://github.com/NavAbility/NavAbilitySDK.py/issues/64.

Apologies on the cross-repo references.

### CODE REVIEW

**Comment by GearsAD** [comment]
@dehann  You'll need to pull this down if you want to review.

**Comment by dehann** [comment]
HI Sam, thanks -- will look and merge.

Cross repo references are good.  I do them all time.  Helps find stuff when referring back.

**Review by dehann — APPROVED** [review]
thanks that worked, there were still two bugs in the code, but i fixed that and will be merging.  I ran through the code locally and check on App, it all worked.  Next step is getting the numerics under regular test.

**Comment by GearsAD** [comment]
Cool :+1:

**Pull request merged**
