### PR TITLE
Final MVP Tut1 notebook fixes

### PR DESCRIPTION
**Pull request by dehann**

### CODE REVIEW

**Comment by dehann** [comment]
Correction, needs DFG v0.18.2 and IIF v0.27.4

**Comment by Affie** [comment]
using GraphPlot should be first

**Comment by Affie** [comment]
"First, we will need some packages: " does not fit with `using` anymore

**Comment by Affie** [comment]
Grammar
image

**Comment by Affie** [comment]
Last output deleted:
image

**Comment by dehann** [comment]
Thanks, fixed on 95a5324

**Pull request merged**
