### PR TITLE
Content for Tut1 SDK.jl (PR required some github gynmastics)

### LINKED ISSUE #46: Content Tutorial 1, SDK.jl
Can populate, 

Once populated, can only close out after SDK.jl v0.4.0
- https://github.com/NavAbility/NavAbilitySDK.jl/issues/86

### PR DESCRIPTION
**Pull request by dehann**
closes #46

### CODE REVIEW

**Comment by dehann** [comment]
Hi @Affie , can you please try this and approve PR when through.

cc @GearsAD

**Comment by Affie** [comment]
Looks like binder is also giving trouble, willl try again later:
image

**Comment by Affie** [comment]
I get a errors local: 
- MethodError: no method matching NavAbilityHttpsClient()
- MethodError: no method matching Variable(::String, ::Symbol)
- UndefVarError: FullNormal not defined
- UndefVarError: waitForCompletion not defined

**Comment by Affie** [comment]
Ahh, it looks like we need a new release on NavAbilitySDK.jl?

**Comment by Affie** [comment]
Ok, I checked out `main` on NavAbilitySDK.jl and errors above are gone, so just igone the comment. 

Needs https://github.com/NavAbility/NavAbilitySDK.jl/issues/86

**Comment by Affie** [comment]
The covariance ellipse sizes in the app are not correct. I'll open an issue.

**Comment by Affie** [comment]
Just as a general comment, do you think we should have screenshots of the app with results in the tutorails?

**Review by Affie — APPROVED** [review]

**Comment by Affie** [comment]
see https://github.com/NavAbility/BinderNotebooks/pull/47/commits/9d1c1927ccde26335614e81cc23d69076f7c34fd

**Comment by jim-hill-r** [comment]
> The covariance ellipse sizes in the app are not correct. I'll open an issue.

Issue https://github.com/NavAbility/NavAbilityApp/issues/28

**Comment by dehann** [comment]
> Just as a general comment, do you think we should have screenshots of the app with results in the tutorails?

Good question, however, my sense is no.  Why: My understanding is we will have a static render of each tutorial already available early on, before visitors get to running code.  Might be some noodling to do there to get the flow right.  Either way, I do not believe it necessary to burden each of the notebooks internally with results.  I want them clean, and force users to try running the code.  The single static render on the way in to the tutorial seems more professional to me.

**Pull request merged**
