### PR TITLE
Update SDK.jl tutorials with simple wrapper api

### PR DESCRIPTION
**Pull request by Affie**
- [x] Tutorial 1
- [x] Tutorial 2
    - [ ] Still need `Mixture`
- [x] Tutorial 3
- [x] Tutorial 4

### CODE REVIEW

**Comment by Affie** [comment]
Stupid vscode didn't revert the output changes I wanted to. Will redo

**Comment by Affie** [comment]
Oops, 3778ef8 should be named Update SDK.jl tut2 with simple wrapper api

**Comment by dehann** [comment]
alright thanks Johan!  Looks good from reading.  I will merge and tag on SDK.jl this afternoon, and from there run this branch as reference check.  merge, and tag from there.  Planning to do it all today.

**Comment by dehann** [comment]
Putting a hold on merge due to unrelated issue on cloud.  Will merge once that is resolved.

**Pull request merged**
