### PR TITLE
content for tutorial 2

### PR DESCRIPTION
**Pull request by dehann**
must convert md to ipynb

xref
- #2

### CODE REVIEW

**Comment by dehann** [comment]
Ah, thanks @Affie !

**Comment by Affie** [comment]
We should discuss what to do with static images, I don't know if linking to external sources is the correct way. But I haven't been able to get images to show up with output.

**Comment by dehann** [comment]
Yeah agreed, the images are part of the bigger visualization discussion.  I'd suggest the images come out of doing the tutorial, rather than just reading as a static document.

I suggest we merge this PR and refine in further PRs?

cc @jim-hill-r

**Review by jim-hill-r — APPROVED** [review]
Excellent!

**Comment by jim-hill-r** [comment]
Just a note. If you leave the outputs in the ipynb, then they will render in the non-interactive website version: [app.navability.io/get-started/tutorials/julia/caesar-api/icra-2-nongaussian](app.navability.io/get-started/tutorials/julia/caesar-api/icra-2-nongaussian)

**Comment by Affie** [comment]
The outputs are there but the images don't seem to work in the notebook. I tried it before, but can't remember now if it was left in this version: https://mybinder.org/v2/gh/NavAbility/BinderNotebooks/22Q1/tut1

**Comment by jim-hill-r** [comment]
> The outputs are there but the images don't seem to work in the notebook. I tried it before, but can't remember now if it was left in this version: https://mybinder.org/v2/gh/NavAbility/BinderNotebooks/22Q1/tut1

I see. No problem. Once  it is in the notebook, we can debug it in separate issues. Merge away!

**Comment by dehann** [comment]
Thanks, apologies that i've been a bit slow getting this far with content.  PRs for sketches of content 
- Tutorial 3, #9  
- Tutorial 4, #10 

I have a good idea for content for Tutorial 3, and more work needed for content for Tutorial 4.

**Comment by dehann** [comment]
Oh, and im sure this Tutorial 2 still needs cosmetic cleanup to make it look and feel like the ICRA tutorials we want.  I feel the content in this PR is a pretty good start for Tutorial 2.  


EDIT: Things like, should the `using IncrementalInference` call be there.  The static images etc.

**Pull request merged**
