### PR TITLE
WIP Fix typos and diffs with other tut 1s

### PR DESCRIPTION
**Pull request by Affie**

### CODE REVIEW

**Comment by dehann** [comment]
more updates went into main again, so just make sure you check this against latest main.  Prevent steaming PRs :-)

**Comment by dehann** [comment]
HI Johan, not sure what is in here, but I just merged a fully working SDK.py Tut1 to main.  I had a bunch of code fixes, a few text fixes.  Bit hard to see with this diff what the diferences are in this PR.  Gitlens in VSCode seems to do a better job.  Could you please confirm if there is anything in this PR that we should still add to Tut1 or can we close and move on.

**Comment by Affie** [comment]
Ok, I’ll rebase and check changes

**Comment by Affie** [comment]
replaced by #55, hope I got everything. Github sucks with notebooks

**Pull request closed without merging**
